#!/bin/sh

#
# ARGUMENTS AND ENVIRONMENT
#

for arg in "$@"
do
     echo "ARG is " $arg
     index=$(echo $arg | cut -f1 -d "=")
     val=$(echo $arg | cut -f2 -d "=")
     
     case $index in
	 --main) SHARPMAKE_MAIN=$val;;
	 *)
     esac
done

echo "SHARPMAKE_MAIN is " $SHARPMAKE_MAIN

# workaround for https://github.com/mono/mono/issues/6752
TERM=xterm

# working directory
SCRIPT_FILE=$(readlink -f "$0")
SCRIPT_DIR=$(dirname "$SCRIPT_FILE")

# relative to script location Sharpmake/util
SHARPMAKE_EXECUTABLE=$SCRIPT_DIR/../bin/Release/Sharpmake.Application.exe

#
# RESULT DEFINITIONS
#

success () {
    echo "Generation succeeded!"
    exit 0
}

error () {
    echo "Generation failed!"
    exit 1
}

#
# ENVIRONMENT TESTS
#

# fail immediately if anything goes wrong
set -e

# mono
which mono > /dev/null
MONO_FOUND=$?
if [ $MONO_FOUND -ne 0 ]; then
    echo "Mono not found!"
    error
fi

#
# GENERATE
#

echo "Generating..."
SM_CMD="mono \"${SHARPMAKE_EXECUTABLE}\" \"/sources(\\\"${SHARPMAKE_MAIN}\\\")\" /verbose"
echo $SM_CMD
eval $SM_CMD || error

success
